a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print("Bitwise AND (&) =", a & b)
print("Bitwise OR (|) =", a | b)
print("Bitwise XOR (^) =", a ^ b)
print("Bitwise NOT (~a) =", ~a)
print("Bitwise NOT (~b) =", ~b)
print("Left Shift (a << 1) =", a << 1)
print("Right Shift (a >> 1) =", a >> 1)